name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - v**
permissions:
  contents: write  # Grant write permission to contents

jobs:
  generate-order:
    name: "Generate Order"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: actions/checkout@v2
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Generate for Golang - Order"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/golang_pb_generator.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./golang_pb_generator.sh order ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com ${{ github.repository }}

  generate-payment:
    name: "Generate Payment"
    runs-on: ubuntu-latest
    needs: generate-order
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: actions/checkout@v2
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Generate for Golang - Payment"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/golang_pb_generator.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./golang_pb_generator.sh payment ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com ${{ github.repository }}

  generate-shipping:
    name: "Generate Shipping"
    runs-on: ubuntu-latest
    needs: generate-payment
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: actions/checkout@v2
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Generate for Golang - Shipping"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/golang_pb_generator.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./golang_pb_generator.sh shipping ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com ${{ github.repository }}
  update-version:
    name: "Update Tag Version"
    runs-on: ubuntu-latest
    needs: generate-shipping
    steps:
      - uses: actions/checkout@v2
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Update tag version"
        shell: bash
        run: git tag -f ${{ env.RELEASE_VERSION }} && git push origin --force --tags